version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: otrs_ollama
    stdin_open: true
    tty: true
    devices:
      - "nvidia.com/gpu=all"
    volumes:
      - ${OLLAMA_HOST_DIR:-./ollama_data}:/root/.ollama
    privileged: true
    ports:
      - 11434:11434
  db:
    build:
      context: db_image
      dockerfile: Dockerfile
    container_name: otrs_db
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    volumes:
      - ${PGDATA_HOST_DIR:-./pgdata}:/var/lib/postgresql/data:Z
    shm_size: '20g'
    command:
      - "-c"
      - "effective_cache_size=10GB"
      - "-c"
      - "shared_buffers=5GB"
      - "-c"
      - "work_mem=512MB"
      - "-c"
      - "max_parallel_workers_per_gather=4"
    restart: always
    depends_on:
      - ollama
